In [ ]:
import pandas as pd
df=pd.read_csv("/archive (6).zip")

In [ ]:
df

ID  Estimated_Insects_Count Crop_Type     Soil_Type  \
0      F00000001                      188    Kharif      Alluvial   
1      F00000003                      209    Kharif      Alluvial   
2      F00000004                      257    Kharif      Alluvial   
3      F00000005                      257    Kharif  Black-Cotton   
4      F00000006                      342    Kharif      Alluvial   
...          ...                      ...       ...           ...   
88853  F00155935                     3337    Kharif      Alluvial   
88854  F00155938                     3516    Kharif      Alluvial   
88855  F00155939                     3516    Kharif      Alluvial   
88856  F00155942                     3702    Kharif      Alluvial   
88857  F00155945                     3895    Kharif      Alluvial   

      Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0               Insecticides                  0                  0   
1               Insecticides                  0                  0   
2               Insecticides                  0                  0   
3               Insecticides                  0                  0   
4               Insecticides                  0                  0   
...                      ...                ...                ...   
88853             Herbicides                 10                 12   
88854             Herbicides                 10                 20   
88855             Herbicides                 15                 40   
88856             Herbicides                 10                 25   
88857             Herbicides                 20                 37   

       Number_Weeks_Quit   Season     Crop_Damage  
0                      0   Summer  Minimal Damage  
1                      0  Monsoon  Partial Damage  
2                      0  Monsoon  Partial Damage  
3                      0  Monsoon  Partial Damage  
4                      0  Monsoon  Partial Damage  
...                  ...      ...             ...  
88853                 44   Winter  Minimal Damage  
88854                 38   Summer  Minimal Damage  
88855                  8  Monsoon  Minimal Damage  
88856                 18   Winter  Minimal Damage  
88857                  7   Winter  Minimal Damage  

[88858 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['Crop_Damage'])
label

array([0, 1, 1, ..., 0, 0, 0])

In [ ]:
df.drop("Crop_Damage", axis=1, inplace=True)
df["Crop_Damage"] = label
df

ID  Estimated_Insects_Count Crop_Type     Soil_Type  \
0      F00000001                      188    Kharif      Alluvial   
1      F00000003                      209    Kharif      Alluvial   
2      F00000004                      257    Kharif      Alluvial   
3      F00000005                      257    Kharif  Black-Cotton   
4      F00000006                      342    Kharif      Alluvial   
...          ...                      ...       ...           ...   
88853  F00155935                     3337    Kharif      Alluvial   
88854  F00155938                     3516    Kharif      Alluvial   
88855  F00155939                     3516    Kharif      Alluvial   
88856  F00155942                     3702    Kharif      Alluvial   
88857  F00155945                     3895    Kharif      Alluvial   

      Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0               Insecticides                  0                  0   
1               Insecticides                  0                  0   
2               Insecticides                  0                  0   
3               Insecticides                  0                  0   
4               Insecticides                  0                  0   
...                      ...                ...                ...   
88853             Herbicides                 10                 12   
88854             Herbicides                 10                 20   
88855             Herbicides                 15                 40   
88856             Herbicides                 10                 25   
88857             Herbicides                 20                 37   

       Number_Weeks_Quit   Season  Crop_Damage  
0                      0   Summer            0  
1                      0  Monsoon            1  
2                      0  Monsoon            1  
3                      0  Monsoon            1  
4                      0  Monsoon            1  
...                  ...      ...          ...  
88853                 44   Winter            0  
88854                 38   Summer            0  
88855                  8  Monsoon            0  
88856                 18   Winter            0  
88857                  7   Winter            0  

[88858 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['Season'])
label

array([1, 0, 0, ..., 0, 2, 2])

In [ ]:
df.drop("Season", axis=1, inplace=True)
df["Season"] = label
df

ID  Estimated_Insects_Count Crop_Type     Soil_Type  \
0      F00000001                      188    Kharif      Alluvial   
1      F00000003                      209    Kharif      Alluvial   
2      F00000004                      257    Kharif      Alluvial   
3      F00000005                      257    Kharif  Black-Cotton   
4      F00000006                      342    Kharif      Alluvial   
...          ...                      ...       ...           ...   
88853  F00155935                     3337    Kharif      Alluvial   
88854  F00155938                     3516    Kharif      Alluvial   
88855  F00155939                     3516    Kharif      Alluvial   
88856  F00155942                     3702    Kharif      Alluvial   
88857  F00155945                     3895    Kharif      Alluvial   

      Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0               Insecticides                  0                  0   
1               Insecticides                  0                  0   
2               Insecticides                  0                  0   
3               Insecticides                  0                  0   
4               Insecticides                  0                  0   
...                      ...                ...                ...   
88853             Herbicides                 10                 12   
88854             Herbicides                 10                 20   
88855             Herbicides                 15                 40   
88856             Herbicides                 10                 25   
88857             Herbicides                 20                 37   

       Number_Weeks_Quit  Crop_Damage  Season  
0                      0            0       1  
1                      0            1       0  
2                      0            1       0  
3                      0            1       0  
4                      0            1       0  
...                  ...          ...     ...  
88853                 44            0       2  
88854                 38            0       1  
88855                  8            0       0  
88856                 18            0       2  
88857                  7            0       2  

[88858 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['ID'])
label

array([    0,     1,     2, ..., 88855, 88856, 88857])

In [ ]:
df.drop("ID", axis=1, inplace=True)
df["ID"] = label
df

Estimated_Insects_Count Crop_Type     Soil_Type Pesticide_Use_Category  \
0                          188    Kharif      Alluvial           Insecticides   
1                          209    Kharif      Alluvial           Insecticides   
2                          257    Kharif      Alluvial           Insecticides   
3                          257    Kharif  Black-Cotton           Insecticides   
4                          342    Kharif      Alluvial           Insecticides   
...                        ...       ...           ...                    ...   
88853                     3337    Kharif      Alluvial             Herbicides   
88854                     3516    Kharif      Alluvial             Herbicides   
88855                     3516    Kharif      Alluvial             Herbicides   
88856                     3702    Kharif      Alluvial             Herbicides   
88857                     3895    Kharif      Alluvial             Herbicides   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Crop_Damage  \
0                      0                  0                  0            0   
1                      0                  0                  0            1   
2                      0                  0                  0            1   
3                      0                  0                  0            1   
4                      0                  0                  0            1   
...                  ...                ...                ...          ...   
88853                 10                 12                 44            0   
88854                 10                 20                 38            0   
88855                 15                 40                  8            0   
88856                 10                 25                 18            0   
88857                 20                 37                  7            0   

       Season     ID  
0           1      0  
1           0      1  
2           0      2  
3           0      3  
4           0      4  
...       ...    ...  
88853       2  88853  
88854       1  88854  
88855       0  88855  
88856       2  88856  
88857       2  88857  

[88858 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['Crop_Type'])
label

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
df.drop("Crop_Type", axis=1, inplace=True)
df["Crop_Type"] = label
df

Estimated_Insects_Count     Soil_Type Pesticide_Use_Category  \
0                          188      Alluvial           Insecticides   
1                          209      Alluvial           Insecticides   
2                          257      Alluvial           Insecticides   
3                          257  Black-Cotton           Insecticides   
4                          342      Alluvial           Insecticides   
...                        ...           ...                    ...   
88853                     3337      Alluvial             Herbicides   
88854                     3516      Alluvial             Herbicides   
88855                     3516      Alluvial             Herbicides   
88856                     3702      Alluvial             Herbicides   
88857                     3895      Alluvial             Herbicides   

       Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Crop_Damage  \
0                      0                  0                  0            0   
1                      0                  0                  0            1   
2                      0                  0                  0            1   
3                      0                  0                  0            1   
4                      0                  0                  0            1   
...                  ...                ...                ...          ...   
88853                 10                 12                 44            0   
88854                 10                 20                 38            0   
88855                 15                 40                  8            0   
88856                 10                 25                 18            0   
88857                 20                 37                  7            0   

       Season     ID  Crop_Type  
0           1      0          0  
1           0      1          0  
2           0      2          0  
3           0      3          0  
4           0      4          0  
...       ...    ...        ...  
88853       2  88853          0  
88854       1  88854          0  
88855       0  88855          0  
88856       2  88856          0  
88857       2  88857          0  

[88858 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['Soil_Type'])
label

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
df.drop("Soil_Type", axis=1, inplace=True)
df["Soil_Type"] = label
df

Estimated_Insects_Count Pesticide_Use_Category  Number_Doses_Week  \
0                          188           Insecticides                  0   
1                          209           Insecticides                  0   
2                          257           Insecticides                  0   
3                          257           Insecticides                  0   
4                          342           Insecticides                  0   
...                        ...                    ...                ...   
88853                     3337             Herbicides                 10   
88854                     3516             Herbicides                 10   
88855                     3516             Herbicides                 15   
88856                     3702             Herbicides                 10   
88857                     3895             Herbicides                 20   

       Number_Weeks_Used  Number_Weeks_Quit  Crop_Damage  Season     ID  \
0                      0                  0            0       1      0   
1                      0                  0            1       0      1   
2                      0                  0            1       0      2   
3                      0                  0            1       0      3   
4                      0                  0            1       0      4   
...                  ...                ...          ...     ...    ...   
88853                 12                 44            0       2  88853   
88854                 20                 38            0       1  88854   
88855                 40                  8            0       0  88855   
88856                 25                 18            0       2  88856   
88857                 37                  7            0       2  88857   

       Crop_Type  Soil_Type  
0              0          0  
1              0          0  
2              0          0  
3              0          1  
4              0          0  
...          ...        ...  
88853          0          0  
88854          0          0  
88855          0          0  
88856          0          0  
88857          0          0  

[88858 rows x 10 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
label = le.fit_transform(df['Pesticide_Use_Category'])
label

array([2, 2, 2, ..., 1, 1, 1])

In [ ]:
df.drop("Pesticide_Use_Category", axis=1, inplace=True)
df["Pesticide_Use_Category"] = label
df

Estimated_Insects_Count  Number_Doses_Week  Number_Weeks_Used  \
0                          188                  0                  0   
1                          209                  0                  0   
2                          257                  0                  0   
3                          257                  0                  0   
4                          342                  0                  0   
...                        ...                ...                ...   
88853                     3337                 10                 12   
88854                     3516                 10                 20   
88855                     3516                 15                 40   
88856                     3702                 10                 25   
88857                     3895                 20                 37   

       Number_Weeks_Quit  Crop_Damage  Season     ID  Crop_Type  Soil_Type  \
0                      0            0       1      0          0          0   
1                      0            1       0      1          0          0   
2                      0            1       0      2          0          0   
3                      0            1       0      3          0          1   
4                      0            1       0      4          0          0   
...                  ...          ...     ...    ...        ...        ...   
88853                 44            0       2  88853          0          0   
88854                 38            0       1  88854          0          0   
88855                  8            0       0  88855          0          0   
88856                 18            0       2  88856          0          0   
88857                  7            0       2  88857          0          0   

       Pesticide_Use_Category  
0                           2  
1                           2  
2                           2  
3                           2  
4                           2  
...                       ...  
88853                       1  
88854                       1  
88855                       1  
88856                       1  
88857                       1  

[88858 rows x 10 columns]

In [ ]:
x=df.drop(['Crop_Damage'],axis=1)
y=df['Crop_Damage']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
Classifier=DecisionTreeClassifier()
Classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = Classifier.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[12643  1819   336]
 [ 1594   742   184]
 [  245   151    58]]
              precision    recall  f1-score   support

           0       0.87      0.85      0.86     14798
           1       0.27      0.29      0.28      2520
           2       0.10      0.13      0.11       454

    accuracy                           0.76     17772
   macro avg       0.42      0.43      0.42     17772
weighted avg       0.77      0.76      0.76     17772



In [ ]:
from sklearn.naive_bayes import GaussianNB
np = GaussianNB()
np.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred2=np.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[14144   654     0]
 [ 2089   431     0]
 [  368    86     0]]
              precision    recall  f1-score   support

           0       0.85      0.96      0.90     14798
           1       0.37      0.17      0.23      2520
           2       0.00      0.00      0.00       454

    accuracy                           0.82     17772
   macro avg       0.41      0.38      0.38     17772
weighted avg       0.76      0.82      0.78     17772



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 100)
rf.fit(x_train,y_train)

RandomForestClassifier()

In [ ]:
y_pred3=rf.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred3))
print(classification_report(y_test,y_pred3))

[[14386   390    22]
 [ 2001   471    48]
 [  317   124    13]]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91     14798
           1       0.48      0.19      0.27      2520
           2       0.16      0.03      0.05       454

    accuracy                           0.84     17772
   macro avg       0.50      0.40      0.41     17772
weighted avg       0.79      0.84      0.80     17772



In [ ]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(x_train, y_train)

XGBClassifier(objective='multi:softprob')

In [ ]:
y_pred4=rf.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(y_test,y_pred4))
print(classification_report(y_test,y_pred4))

[[14386   390    22]
 [ 2001   471    48]
 [  317   124    13]]
              precision    recall  f1-score   support

           0       0.86      0.97      0.91     14798
           1       0.48      0.19      0.27      2520
           2       0.16      0.03      0.05       454

    accuracy                           0.84     17772
   macro avg       0.50      0.40      0.41     17772
weighted avg       0.79      0.84      0.80     17772



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=3)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred=model.predict(x_test)
results=pd.DataFrame({'Actual':y_test,'Predictions':y_pred})
results.head(5)

Actual  Predictions
47348       0            0
28521       0            0
69698       0            0
64330       0            0
3651        0            0

In [ ]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[13994   761    43]
 [ 1931   557    32]
 [  351    96     7]]


In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.95      0.90     14798
           1       0.39      0.22      0.28      2520
           2       0.09      0.02      0.03       454

    accuracy                           0.82     17772
   macro avg       0.45      0.39      0.40     17772
weighted avg       0.77      0.82      0.79     17772



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=9)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[14429   362     7]
 [ 2280   238     2]
 [  410    44     0]]


In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.84      0.98      0.90     14798
           1       0.37      0.09      0.15      2520
           2       0.00      0.00      0.00       454

    accuracy                           0.83     17772
   macro avg       0.40      0.36      0.35     17772
weighted avg       0.75      0.83      0.77     17772



In [ ]:
from sklearn.linear_model import LogisticRegression
Classifier=LogisticRegression(solver='liblinear')
Classifier.fit(x_train,y_train)

LogisticRegression(solver='liblinear')

In [ ]:
y_test_hat=Classifier.predict(x_test)
res=pd.DataFrame({'Actual':y_test,'Predictions':y_test_hat})
res.head(5)

Actual  Predictions
47348       0            0
28521       0            0
69698       0            0
64330       0            0
3651        0            0

In [ ]:
y_train_hat=Classifier.predict(x_train)
print(accuracy_score(y_train,y_train_hat))

0.8326112033311763


In [ ]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_test_hat))

0.829113211793833
